# Generated by Django 4.1.7 on 2023-03-05 11:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=150, verbose_name='Категория атауы')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=255, verbose_name='Курс атауы')),
                ('courseDescription', models.TextField(verbose_name='Курстың сипаттамасы')),
                ('courseLogo', models.ImageField(upload_to='images/', verbose_name='Курс логотипі')),
                ('postDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Курстың жариялау уақыты мен күні')),
                ('courseAge', models.IntegerField(verbose_name='Жас')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainCoreApp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курстар',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelName', models.CharField(max_length=100, verbose_name='Деңгей атауы')),
            ],
            options={
                'verbose_name': 'Деңгей',
                'verbose_name_plural': 'Деңгейлер',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(max_length=255, verbose_name='Модуль атауы')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainCoreApp.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модульдер',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonName', models.CharField(max_length=255, verbose_name='Сабақ тақырыбы')),
                ('videoLesson', models.CharField(blank=True, max_length=500, null=True, verbose_name='Видео сабақ сілтемесі')),
                ('practiceLesson', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Практикалық сабақ сипаттамасы')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainCoreApp.course', verbose_name='Курс')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainCoreApp.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Сабақ',
                'verbose_name_plural': 'Сабақтар',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainCoreApp.level', verbose_name='Деңгей'),
        ),
    ]
