# Generated by Django 4.1.7 on 2023-03-06 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoreApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='module',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
